### ISSUE TITLE
accProcess file error when parsing a data in the current folder

### ISSUE THREAD

**Issue by angerhang** [activityMonitoring/biobankAccelerometerAnalysis#182]
```
data/
   sample.cwa.gz
```

When I tried running `accProcess sample.cwa.gz` inside the data directory, the following error appears

```bash
(home_env) hangy@NDPH8334 ~ % cd Data
(home_env) hangy@NDPH8334 Data % accProcess sample.cwa.gz --deleteIntermediateFiles False --useFilter False --npyOutput True --sampleRate 30 --csvSampleRate 30 --epochPeriod 30
/Users/hangy/opt/miniconda3/envs/home_Env/lib/python3.9/site-packages/accelerometer/accProcess.py:245: UserWarning: Skipping lowpass filter (--useFilter False) as sampleRate too low (<= 40)
  warnings.warn("Skipping lowpass filter (--useFilter False) as sampleRate too low (<= 40)")
Traceback (most recent call last):
  File "/Users/hangy/opt/miniconda3/envs/home_env/bin/accProcess", line 8, in <module>
    sys.exit(main())
  File "/Users/hangy/opt/miniconda3/envs/home_Env/lib/python3.9/site-packages/accelerometer/accProcess.py", line 297, in main
    assert os.access(path, os.W_OK), (
AssertionError: Either folder '' does not exist or you do not have write permission

```

However, when I go up on folder, the parsing was OK.
```
(home_env) hangy@NDPH8334 Data % cd ..
(home_env) hangy@NDPH8334 ~ % accProcess data/sample.cwa.gz --deleteIntermediateFiles False --useFilter False --npyOutput True --sampleRate 30 --csvSampleRate 30 --epochPeriod 30 

/Users/hangy/opt/miniconda3/envs/home_Env/lib/python3.9/site-packages/accelerometer/accProcess.py:245: UserWarning: Skipping lowpass filter (--useFilter False) as sampleRate too low (<= 40)
  warnings.warn("Skipping lowpass filter (--useFilter False) as sampleRate too low (<= 40)")
Processing file 'data/sample.cwa.gz' with these arguments:

activityClassification : True
activityModel   : walmsley
calOffset       : [0.0, 0.0, 0.0]
calSlope        : [1.0, 1.0, 1.0]
calTemp         : [0.0, 0.0, 0.0]
calibrationSphereCriteria : 0.3
csvSampleRate   : 30.0
```

Seems like an unexpected behaviour, should investigate further.

**Comment by chanshing** [comment]
Ah I found this too and it's in my TODO list.
