### ISSUE TITLE
Java DateTimeException

### ISSUE THREAD

**Issue by sehamsick** [activityMonitoring/biobankAccelerometerAnalysis#196]
Hi Everyone,

As I processed a batch of files with the `accProcess` command, I experienced the following java exceptions in some files. It's interesting that it nevertheless successfully processed everything, irrespective of these error messages. Not all files are affected.

I'm wondering how this might affect the results, since it does not abort the process?
For example, I could imagine if these 0 values come from the fact that e.g. the device is not worn, it should not be a issue, does anyone know more?

```
block err @ 2015-04-26T11:59:02.760467529+01:00[Europe/London]: java.time.DateTimeException: Invalid value for DayOfMonth (valid values 1 - 28/31): 0  java.time.DateTimeException: Invalid value for DayOfMonth (valid values 1 - 28/31): 0
    at java.base/java.time.temporal.ValueRange.checkValidValue(ValueRange.java:311)
    at java.base/java.time.temporal.ChronoField.checkValidValue(ChronoField.java:717)
    at java.base/java.time.LocalDate.of(LocalDate.java:270)
    at java.base/java.time.LocalDateTime.of(LocalDateTime.java:336)
    at AxivityReader.getCwaTimestamp(AxivityReader.java:345)
    at AxivityReader.readCwaBuffer(AxivityReader.java:227)
    at AxivityReader.readCwaEpochs(AxivityReader.java:58)
    at AccelerometerParser.main(AccelerometerParser.java:215)`
```
```
    block err @ 2015-02-08T13:48:43.407653808Z[Europe/London]: java.time.DateTimeException: Invalid value for MonthOfYear (valid values 1 - 12): 0
java.time.DateTimeException: Invalid value for MonthOfYear (valid values 1 - 12): 0
    at java.base/java.time.temporal.ValueRange.checkValidValue(ValueRange.java:311)
    at java.base/java.time.temporal.ChronoField.checkValidValue(ChronoField.java:717)
    at java.base/java.time.LocalDate.of(LocalDate.java:269)
    at java.base/java.time.LocalDateTime.of(LocalDateTime.java:336)
    at AxivityReader.getCwaTimestamp(AxivityReader.java:345)
    at AxivityReader.readCwaBuffer(AxivityReader.java:227)
    at AxivityReader.readCwaEpochs(AxivityReader.java:58)
    at AccelerometerParser.main(AccelerometerParser.java:215)
```    

Thanks in advance!

**Comment by aidendoherty** [comment]
Many thanks for your question @sehamsick/ One sample in each “sector” of data (typically 120 samples for the Biobank configuration), is assigned a timestamp. As you have identified, on some rare occasions there can be an erroneous recording of the timestamp (that is not fixed by the error correcting checksums). From memory I believe we exclude this sample of data. However, the effect is almost certainly negligible as this relates to just a couple of seconds of missing data out of a 7 day wear-period (particularly in the context that missing data imputation is run later in the processing pipeline).

I do hope this helps.
