### ISSUE TITLE
circadianRhythms.calculatePSD() error!

### ISSUE THREAD

**Issue by JianWang2016** [activityMonitoring/biobankAccelerometerAnalysis#27]
Hi, 

Thanks much for the Cicardian Rhythm feature.  Can't wait to use it.

I tried to run accProcess.py with --psd TRUE --fourierFrequency TRUE --fourierWithAcc True --m10l5 True and getting the following error message (please note I changed my file path with path-to).  Please note I don't have such an error message if I use the default (FALSE) for all four inputs.

Is it correct to turn all of the four data types to TRUE at the same time?  All python packages are most-up-to-date.  I'd appreciate any suggestions to fix this. 

Traceback (most recent call last):
  File "accProcess.py", line 414, in <module>
    main()  # Standard boilerplate to call the main() function to begin the program.
  File "accProcess.py", line 339, in main
    epochData, labels = accelerometer.summariseEpoch.getActivitySummary(
  File "/path-to/biobankAccelerometerAnalysis/accelerometer/summariseEpoch.py", line 130, in getActivitySummary
    circadianRhythms.calculatePSD(e, epochPeriod, fourierWithAcc, labels, summary)
  File "/path-to/biobankAccelerometerAnalysis/accelerometer/circadianRhythms.py", line 43, in calculatePSD
    res = np.sum(np.exp(e) * y, axis=-1)/n
  File "<__array_function__ internals>", line 5, in sum
  File "/path-to/conda_actigraphy/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2228, insum
    return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims,
  File "/path-to/conda_actigraphy/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 88, in _wrapreduction
    return reduction(axis=axis, out=out, **passkwargs)
  File "/path-to/conda_actigraphy/lib/python3.8/site-packages/pandas/core/generic.py", line 11177, in stat_func
    return self._reduce(
  File "/path-to/conda_actigraphy/lib/python3.8/site-packages/pandas/core/series.py", line 3870, in _reduce
    self._get_axis_number(axis)
  File "/path-to/conda_actigraphy/lib/python3.8/site-packages/pandas/core/generic.py", line 407, in _get_axis_number
    raise ValueError(f"No axis named {axis} for object type {cls}")
ValueError: No axis named -1 for object type <class 'pandas.core.series.Series'>

**Comment by chanshing** [comment]
@JianWang2016 Thanks for spotting this. The issue was that a pandas frame was not being converted to numpy before a numpy routine call. I just issued a PR to fix this https://github.com/activityMonitoring/biobankAccelerometerAnalysis/pull/34
